UI/WebStore/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol;
using WebStore.Domain.Identity;
using WebStore.Domain.ViewModels;
using WebStore.Interfaces.Services;
using WebStore.Services.Services;

namespace WebStore.Areas.Admin.Controllers;

[Area("Admin"), Authorize(Roles = Role.Administrators)]
public class ProductsController : Controller
{
    private readonly IProductData _productData;
    private readonly ILogger<ProductsController> _logger;

    public ProductsController(IProductData productData, ILogger<ProductsController> logger)
    {
        _productData = productData;
        _logger = logger;
    }

    public IActionResult Index()
    {
        var productsView = _productData.GetProducts().Products.ToView();
        return View(productsView);
    }

    public IActionResult Edit(int id)
    {
        var productView = _productData.GetProductById(id).ToView();
        return View(productView);
    }

    [HttpPost]
    public IActionResult Edit(ProductViewModel productView)
    {
        if (!ModelState.IsValid)
            return View(productView);
        var product = productView.FromView();
        var brand = _productData.GetBrands().FirstOrDefault(b => b.Name.Equals(product.Brand.Name));
        var section = _productData.GetSections().FirstOrDefault(s => s.Name.Equals(product.Section.Name));
        product.Brand = brand;
        product.Section = section;
        _productData.Edit(product);
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        var productView = _productData.GetProductById(id).ToView();
        return View(productView);
    }
    
    [HttpPost]
    public IActionResult Delete(ProductViewModel productView)
    {
        var product = productView.FromView();
        _productData.Delete(product.Id);
        return RedirectToAction("Index");
    }
    
    public IActionResult Add(string name, string? brand, string section, string? imageUrl, decimal price)
    {
        var productView = new ProductViewModel
        {
            Name = name,
            Brand = brand,
            Section = section,
            ImageUrl = imageUrl,
            Price = price
        };
        return View(productView);
    }
    
    [HttpPost]
    public IActionResult Add(ProductViewModel productView)
    {
        if (!ModelState.IsValid)
            return View(productView);
        var product = productView.FromView();
        var brand = _productData.GetBrands().FirstOrDefault(b => b.Name.Equals(product.Brand.Name));
        var section = _productData.GetSections().FirstOrDefault(s => s.Name.Equals(product.Section.Name));
        product.Brand = brand;
        product.Section = section;
        _productData.Add(product);
        return RedirectToAction("Index");
    }
}

UI/WebStore/Components/BrandsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain.Entities;
using WebStore.Domain.ViewModels;
using WebStore.Interfaces.Services;

namespace WebStore.Components;

public class BrandsViewComponent : ViewComponent
{
    private readonly IEnumerable<Brand>? _Brands;
    public BrandsViewComponent(IProductData brands)
    {
        _Brands = brands.GetBrands();
    }

    public IViewComponentResult Invoke(string brandId)
    {
        ViewBag.brandId = (int.TryParse(brandId, out var id) ? id : (int?) null)!;
        return View(GetBrands());
    }

    private IEnumerable<BrandViewModel> GetBrands() => _Brands.OrderBy(b => b.Order).Select(b => new BrandViewModel
    {
        Id = b.Id,
        Name = b.Name,
    });
}

UI/WebStore/Controllers/BlogsController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebStore.Controllers
{
    public class BlogsController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Title = "Blog List";
            return View("~/Views/Blogs/Index.cshtml");
        }

        public IActionResult Blog()
        {
            ViewBag.Title = "Blog Single";
            return View("~/Views/Blogs/Blog.cshtml");
        }
    }
}

UI/WebStore/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using WebStore.Domain;
using WebStore.Domain.Entities;
using WebStore.Domain.ViewModels;
using WebStore.Interfaces.Services;
using WebStore.Services.Services;

namespace WebStore.Controllers
{
    public class ShopController : Controller
    {
        private const string CatalogPageSize = "CatalogPageSize";
        private readonly IProductData _ProductData;
        private readonly IConfiguration _configuration;

        public ShopController(IProductData productData, IConfiguration configuration)
        {
            _ProductData = productData;
            _configuration = configuration;
        }
        public IActionResult Index(int? brandId, int? sectionId, int page = 1, int? pageSize = null)
        {
            var filter = new ProductFilter
            {
                BrandId = brandId,
                SectionId = sectionId,
                Page = page,
                PageSize = pageSize ?? 
                           (int.TryParse(_configuration[CatalogPageSize], out var pSize)? pSize : null)
            };
            var (products,totalCount) = _ProductData.GetProducts(filter);
            var productsCatalog = new CatalogViewModel
            {
                BrandId = brandId,
                SectionId = sectionId,
                Products = products.OrderBy(p => p.Order).ToView(),
                PageViewModel = new PageViewModel
                {
                    Page = page,
                    PageSize = filter.PageSize ?? 0,
                    TotalCount = totalCount
                }
            };
            return View(productsCatalog);
        }

        public IActionResult Checkout()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            var product = _ProductData.GetProductById(id);
            if (product is null)
                return NotFound();
            return View(product.ToView());
        }

        public IActionResult GetProductsView(int? brandId, int? sectionId, int page = 1, int? pageSize = null)
        {
            var products = GetProductViewModels(brandId, sectionId, page, pageSize);
            return PartialView("Partial/_Products",products);
        }

        private IEnumerable<ProductViewModel> GetProductViewModels(int? brandId, int? sectionId, int page,
            int? pageSize)
        {
            var products = _ProductData.GetProducts(new ProductFilter
            {
                BrandId = brandId,
                SectionId = sectionId,
                Page = page,
                PageSize = pageSize ?? _configuration.GetValue(CatalogPageSize, 6),
            });
            return products.Products.OrderBy(p => p.Order).ToView()!;
        }
    }
}

UI/WebStore/Controllers/WebAPIController.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Interfaces.TestAPI;

namespace WebStore.Controllers;

public class WebApiController : Controller
{
    private readonly IValueService _valueService;

    public WebApiController(IValueService valueService)
    {
        _valueService = valueService;
    }
    // GET
    public IActionResult Index()
    {
        var values = _valueService.GetValues();
        return View(values);
    }
}

UI/WebStore/Views/Shared/Partial/_Footer.cshtml
	<footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>e</span>-shopper</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="~/images/home/iframe1.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="~/images/home/iframe2.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="~/images/home/iframe3.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="~/images/home/iframe4.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="~/images/home/map.png" alt="" />
							<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<li><a href="#">Change Location</a></li>
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<li><a href="#">Billing System</a></li>
								<li><a href="#">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>
								<li><a href="#">Affillate Program</a></li>
								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
					<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
				</div>
			</div>
		</div>
		
	</footer><!--/Footer-->

UI/WebStore/Views/Shared/Partial/_Header.cshtml
<header id="header">
    <!--header-->
    <div class="header_top">
        <!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li>
                                <a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-envelope"></i> info@domain.com</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="#">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-linkedin"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-dribbble"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-google-plus"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle">
        <!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a asp-controller="Home" asp-action="Index">
                            <img src="~/images/home/logo.png" alt=""/>
                        </a>
                    </div>
                    <div class="btn-group pull-right">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                USA
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="#">Canada</a>
                                </li>
                                <li>
                                    <a href="#">UK</a>
                                </li>
                            </ul>
                        </div>

                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                DOLLAR
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="#">Canadian Dollar</a>
                                </li>
                                <li>
                                    <a href="#">Pound</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                 <vc:user-info></vc:user-info>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <partial name="Partial/_MainMenu"/>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search"/>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

UI/WebStore/Views/Shared/Partial/_LeftSideBar.cshtml
<div class="left-sidebar">
    <h2>Category</h2>

    <vc:sections section-id="@Context.Request.Query["sectionId"]"/>
					
    <vc:brands brand-id="@Context.Request.Query["brandId"]"/>

    <vc:price-range/>
						
    <vc:shipping/>
					
</div>

UI/WebStore/Views/Shared/Partial/_MainMenu.cshtml
<div class="mainmenu pull-left">
    <ul class="nav navbar-nav collapse navbar-collapse">
        <li>
            <a ws-is-active-route asp-controller="Home" asp-action="Index" class="active">Home</a>
        </li>
        <li class="dropdown">
            <a ws-is-active-route ws-ignore-action asp-controller="Shop" asp-action="Index">Shop<i class="fa fa-angle-down"></i></a>
            <ul role="menu" class="sub-menu">
                <li>
                    <a ws-is-active-route asp-controller="Shop" asp-action="Index">Products</a>
                </li>
                <li>
                    <a ws-is-active-route asp-controller="Shop" asp-action="Details">Product Details</a>
                </li>
                <li>
                    <a ws-is-active-route asp-controller="Shop" asp-action="Checkout">Checkout</a>
                </li>
                <li>
                    <a ws-is-active-route asp-controller="Cart" asp-action="Index">Cart</a>
                </li>
                <li>
                    <a ws-is-active-route asp-controller="Account" asp-action="Login">Login</a>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a ws-is-active-route asp-controller="Blogs" asp-action="Index">
                Blog<i class="fa fa-angle-down"></i>
            </a>
            <ul role="menu" class="sub-menu">
                <li>
                    <a ws-is-active-route asp-controller="Blogs" asp-action="Index">Blog List</a>
                </li>
                <li>
                    <a ws-is-active-route asp-controller="Blogs" asp-action="Blog">Blog Single</a>
                </li>
            </ul>
        </li>
        <li>
            <a ws-is-active-route asp-controller="NotFound" asp-action="Index">404</a>
        </li>
        <li>
            <a ws-is-active-route asp-controller="ContactUs" asp-action="Index">Contact</a>
        </li>
        <li>
            <a ws-is-active-route asp-controller="Employee" asp-action="Index">Employees</a>
        </li>
        <li>
            <a asp-controller="WebApi" class="@IsActive("WebApi")" asp-action="Index">WebAPI</a>
        </li>
        <li>
            <a ws-is-active-route asp-controller="AjaxTest" asp-action="Index">AJAX</a>
        </li>
        <li>
            <a ws-is-active-route asp-controller="AjaxTest" asp-action="Chat">Chat</a>
        </li>
    </ul>
</div>

@functions
{
    string? IsActive(string controllerName, string actionName = "Index")
    {
        return Equals(ViewContext.RouteData.Values["Controller"], controllerName)
               && Equals(ViewContext.RouteData.Values["Action"], actionName)
            ? "active"
            : null;
    }
}

UI/WebStore/Views/Shared/Partial/_Products.cshtml
@model IEnumerable<WebStore.Domain.ViewModels.ProductViewModel>

<div class="features_items">
    <!--features_items-->
    <h2 class="title text-center">Products</h2>
    @foreach (var product in Model)
    {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="~/images/shop/@product.ImageUrl" alt=""/>
                        <h2>@product.Price</h2>
                        <p>
                            <a asp-controller="Shop" asp-action="Details"
                               asp-route-id="@product.Id"
                               asp-route-sectionId="@Context.Request.Query["brandId"]"
                               asp-route-sectionId="@Context.Request.Query["sectionId"]">
                                @product.Name
                            </a>
                        </p>
                        <a class="btn btn-default add-to-cart"
                           asp-action="Add"
                           asp-controller="Cart"
                           asp-route-id="@product.Id"
                           data-id="@product.Id">
                            <i class="fa fa-shopping-cart"></i>Add to cart
                        </a>
                    </div>
                    <div class="product-overlay">
                        <div class="overlay-content">
                            <h2>@product.Price</h2>
                            <p>
                                <a asp-controller="Shop" asp-action="Details" 
                                   asp-route-id="@product.Id"
                                   asp-route-brandId="@Context.Request.Query["brandId"]"
                                   asp-route-sectionId="@Context.Request.Query["sectionId"]">
                                    @product.Name
                                </a>
                            </p>
                            <a class="btn btn-default add-to-cart"
                               asp-action="Add"
                               asp-controller="Cart"
                               asp-route-id="@product.Id"
                               data-id="@product.Id">
                                <i class="fa fa-shopping-cart"></i>Add to cart
                            </a>
                        </div>
                    </div>
                </div>
                <div class="choose">
                    <ul class="nav nav-pills nav-justified">
                        <li>
                            <a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-plus-square"></i>Add to compare</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    }

</div><!--features_items-->

UI/WebStore/Views/Shared/Partial/_Scripts.cshtml
<script src="~/lib/jquery/jquery.js"></script>
<script src="~/lib/jquery/jquery.min.js"></script>
<script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
<script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/lib/scrollup/jquery.scrollUp.min.js"></script>
<script src="~/js/jquery.prettyPhoto.js"></script>


<environment include="Development">
    <script src="~/js/main.js" asp-append-version="true"></script>
    <script src="~/js/price-range.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="~/js/site.min.js.gz" asp-append-version="true"></script>
</environment>

<script src="~/js/Cart/CartLogic.js" asp-append-version="true"></script>
<script>
$(function (){
    Cart.init({
        getCartViewLink: "@Url.Action("GetCartView","Cart")",
        addToCartLink: "@Url.Action("AddApi","Cart")",
        incrementItemLink: "@Url.Action("AddApi","Cart")",
        decrementItemLink: "@Url.Action("DecrementApi","Cart")",
        removeFromCartLink: "@Url.Action("RemoveApi","Cart")"
    });
})
</script>

UI/WebStore/Views/Shared/Partial/_Styles.cshtml
<link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<link href="~/css/prettyPhoto.css" rel="stylesheet">


<environment include="Development">
    <link href="~/css/price-range.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/responsive.css" rel="stylesheet" asp-append-version="true">
</environment>

<environment exclude="Development">
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true">
</environment>